all: comm_progs

comm_progs:
	g++ -o contenful.exe contenful.cpp -lcurl

# docker run -it --rm -v C:\dev\cursostec\estructuras:/home gcc bash
# apt update -y
# app install curl

# cd C:/Users/Yeiner/OneDrive/Escritorio/"Caso 5"/socket

# make
# ./contenful.exe